// THIS FILE WAS GENERATED BY qrpc - DO NOT EDIT!
package qmodel

import (
	"context"
	"github.com/google/uuid"
	"github.com/stausee1337/qrpc/qrpc"
	"net/http"
)

type ScriptServiceQueries interface {
	List(ctx context.Context) (*[]Script, error)
	Get(ctx context.Context, uuid uuid.UUID) (*Script, error)
}

type ScriptServiceMutation interface {
	SaveScores(ctx context.Context, scriptId uuid.UUID, divisionIdx uint, newScores []uint) error
	Rename(ctx context.Context, uuid uuid.UUID, name string) error
	Create(ctx context.Context, script Script) (*uuid.UUID, error)
	Delete(ctx context.Context, uuid uuid.UUID) error
}

func CreateScriptService(queries ScriptServiceQueries, mutations ScriptServiceMutation) *qrpc.Service {
	return qrpc.NewService(
		"script",
		qrpc.BindResolver(qrpc.OpQuery, queries, еееResolveScriptServiceQuery),
		qrpc.BindResolver(qrpc.OpMutation, mutations, еееResolveScriptServiceMutation),
	)
}

func еееResolveScriptServiceQuery(p ScriptServiceQueries, query string) http.Handler {
	switch query {
	case "list":
		return qrpc.MakeHandler(func(ctx context.Context) qrpc.Response {
			data, err := p.List(ctx)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return qrpc.WrapData(data)
		})
	case "get":
		type input struct {
			Uuid uuid.UUID `json:"uuid"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			data, err := p.Get(ctx, args.Uuid)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return qrpc.WrapData(data)

		})
	default:
		return nil
	}
}

func еееResolveScriptServiceMutation(p ScriptServiceMutation, mutation string) http.Handler {
	switch mutation {
	case "saveScores":
		type input struct {
			ScriptId    uuid.UUID `json:"scriptId"`
			DivisionIdx uint      `json:"divisionIdx"`
			NewScores   []uint    `json:"newScores"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			err := p.SaveScores(ctx, args.ScriptId, args.DivisionIdx, args.NewScores)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return nil
		})
	case "rename":
		type input struct {
			Uuid uuid.UUID `json:"uuid"`
			Name string    `json:"name"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			err := p.Rename(ctx, args.Uuid, args.Name)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return nil
		})
	case "create":
		type input struct {
			Script Script `json:"script"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			data, err := p.Create(ctx, args.Script)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return qrpc.WrapData(data)

		})
	case "delete":
		type input struct {
			Uuid uuid.UUID `json:"uuid"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			err := p.Delete(ctx, args.Uuid)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return nil
		})
	default:
		return nil
	}
}

type AuthServiceMutation interface {
	Signin(ctx context.Context, username string, password string) (*struct {
		Variant1 *AuthSuccess `json:"variant1,omitempty"`
		Variant2 *AuthError   `json:"variant2,omitempty"`
	}, error)
	Signup(ctx context.Context, username string, password string) (*struct {
		Variant1 *AuthSuccess `json:"variant1,omitempty"`
		Variant2 *AuthError   `json:"variant2,omitempty"`
	}, error)
	Refresh(ctx context.Context, refreshToken string) (*AuthSuccess, error)
	Logout(ctx context.Context, refreshToken string) error
}

func CreateAuthService(mutations AuthServiceMutation) *qrpc.Service {
	return qrpc.NewService(
		"auth",
		qrpc.BindResolver(qrpc.OpMutation, mutations, еееResolveAuthServiceMutation),
	)
}

func еееResolveAuthServiceMutation(p AuthServiceMutation, mutation string) http.Handler {
	switch mutation {
	case "signin":
		type input struct {
			Username string `json:"username"`
			Password string `json:"password"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			data, err := p.Signin(ctx, args.Username, args.Password)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return qrpc.WrapData(data)

		})
	case "signup":
		type input struct {
			Username string `json:"username"`
			Password string `json:"password"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			data, err := p.Signup(ctx, args.Username, args.Password)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return qrpc.WrapData(data)

		})
	case "refresh":
		type input struct {
			RefreshToken string `json:"refreshToken"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			data, err := p.Refresh(ctx, args.RefreshToken)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return qrpc.WrapData(data)

		})
	case "logout":
		type input struct {
			RefreshToken string `json:"refreshToken"`
		}
		return qrpc.MakeInputHandler(func(ctx context.Context, args input) qrpc.Response {
			err := p.Logout(ctx, args.RefreshToken)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return nil
		})
	default:
		return nil
	}
}

type UserServiceQueries interface {
	Get(ctx context.Context) (*User, error)
}

func CreateUserService(queries UserServiceQueries) *qrpc.Service {
	return qrpc.NewService(
		"user",
		qrpc.BindResolver(qrpc.OpQuery, queries, еееResolveUserServiceQuery),
	)
}

func еееResolveUserServiceQuery(p UserServiceQueries, query string) http.Handler {
	switch query {
	case "get":
		return qrpc.MakeHandler(func(ctx context.Context) qrpc.Response {
			data, err := p.Get(ctx)
			if err != nil {
				return qrpc.WrapError(err)
			}

			return qrpc.WrapData(data)
		})
	default:
		return nil
	}
}
