// THIS FILE WAS GENERATED BY qrpc - DO NOT EDIT!
package qmodel

import (
	"github.com/google/uuid"
)

type Script struct {
	Uuid      uuid.UUID  `json:"uuid"`
	Name      string     `json:"name"`
	CreatedAt float64    `json:"createdAt"`
	Divisions []Division `json:"divisions"`
}

type Division struct {
	Name           string        `json:"name"`
	Description    string        `json:"description"`
	TextCues       []TextCuePair `json:"textCues"`
	PreviousTotals []uint        `json:"previousTotals"`
}

type TextCuePair struct {
	Request        *TextCue `json:"request"`
	Response       TextCue  `json:"response"`
	PreviousScores []uint   `json:"previousScores"`
}

type TextCue struct {
	Actors []string `json:"actors"`
	Text   string   `json:"text"`
}

type User struct {
	Uuid     uuid.UUID `json:"uuid"`
	Username string    `json:"username"`
	Verified bool      `json:"verified"`
}

type AuthError string

const (
	AuthErrorUSERNAMEMALFORMED     AuthError = "USERNAME_MALFORMED"
	AuthErrorWEAKPASSWORD          AuthError = "WEAK_PASSWORD"
	AuthErrorINVALIDCREDENTIALS    AuthError = "INVALID_CREDENTIALS"
	AuthErrorUSERNAMEALREADYEXISTS AuthError = "USERNAME_ALREADY_EXISTS"
	AuthErrorTOKENEXPIRED          AuthError = "TOKEN_EXPIRED"
	AuthErrorUNAUTHORIZED          AuthError = "UNAUTHORIZED"
)

type AuthSuccess struct {
	UserId       uuid.UUID `json:"userId"`
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiresAt    float64   `json:"expiresAt"`
}
