version: "3.9"
services:
  server:
    image: ghcr.io/stausee1337/quipt-frontend:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/quipt.app/fullchain.pem:/etc/ssl/quipt.app-letsencrypt.crt:ro
      - /etc/letsencrypt/live/quipt.app/privkey.pem:/etc/ssl/quipt.app-letsencrypt.key:ro

      - /etc/letsencrypt/live/api.quipt.app/fullchain.pem:/etc/ssl/api.quipt.app-letsencrypt.crt:ro
      - /etc/letsencrypt/live/api.quipt.app/privkey.pem:/etc/ssl/api.quipt.app-letsencrypt.key:ro

      - ~/nginx/:/var/log/nginx/
  backend:
    image: ghcr.io/stausee1337/quipt-backend:latest
    environment:
      - QUIPT_SERVER_HOST="0.0.0.0"
      - QUIPT_SERVER_PORT=8000
      - QUIPT_CORS_HOST="https://quipt.app"
      - QUIPT_DOCUMENT_DB_USER="user"
      - QUIPT_DOCUMENT_DB_PASSWORD="password123"
      - QUIPT_DOCUMENT_DB_HOST="document_db"
      - QUIPT_DOCUMENT_DB_PORT="10260"
      - QUIPT_REDIS_HOST="redis"
      - QUIPT_REDIS_PORT="6379"
      - QUIPT_AUTH_SECRET="<supply production auth secret>"
    depends_on:
      - document_db
      - redis
  document_db:
    image: ghcr.io/microsoft/documentdb/documentdb-local:latest
    command: --username user --password password123
    volumes:
      - ~/documentdb:/var/lib/documentdb
  redis:
    image: redis
    volumes:
      - ~/cache:/data

