syntax = "proto3";

option go_package = "github.com/stausee1337/quipt/gen/protos";

package auth;

message User {
  string id = 1;
  string username = 2;
  bool verified = 3;
}

message SigninRequest {
  string username = 1;
  string password = 2;
}

message SignupRequest {
  string username = 1;
  string password = 2;
}

message AuthSuccess {
  string userId = 1;
  string accessToken = 2;
  string refreshToken = 3;
  int64 expiresAt = 4;
}

enum AuthErrorCode {
  USERNAME_MALFORMED = 0;
  WEAK_PASSWORD = 1;
  INVALID_CREDENTIALS = 2;
  USERNAME_ALREADY_EXISTS = 3;
  TOKEN_EXPIRED = 4;
  UNAUTHORIZED = 5;
}

// Generic error structure
message AuthError {
  AuthErrorCode code = 1;
  string message = 2;
}

