// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: scripts.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptErrorCode int32

const (
	ScriptErrorCode_ID_MALFORMED           ScriptErrorCode = 0
	ScriptErrorCode_UNKNOWN_SCRIPT         ScriptErrorCode = 1
	ScriptErrorCode_DIVISION_OUT_OF_BOUNDS ScriptErrorCode = 2
	ScriptErrorCode_INVALID_SCORE_DATA     ScriptErrorCode = 3
	ScriptErrorCode_INVALID_SCRIPT_NAME    ScriptErrorCode = 4
)

// Enum value maps for ScriptErrorCode.
var (
	ScriptErrorCode_name = map[int32]string{
		0: "ID_MALFORMED",
		1: "UNKNOWN_SCRIPT",
		2: "DIVISION_OUT_OF_BOUNDS",
		3: "INVALID_SCORE_DATA",
		4: "INVALID_SCRIPT_NAME",
	}
	ScriptErrorCode_value = map[string]int32{
		"ID_MALFORMED":           0,
		"UNKNOWN_SCRIPT":         1,
		"DIVISION_OUT_OF_BOUNDS": 2,
		"INVALID_SCORE_DATA":     3,
		"INVALID_SCRIPT_NAME":    4,
	}
)

func (x ScriptErrorCode) Enum() *ScriptErrorCode {
	p := new(ScriptErrorCode)
	*p = x
	return p
}

func (x ScriptErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScriptErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_scripts_proto_enumTypes[0].Descriptor()
}

func (ScriptErrorCode) Type() protoreflect.EnumType {
	return &file_scripts_proto_enumTypes[0]
}

func (x ScriptErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScriptErrorCode.Descriptor instead.
func (ScriptErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{0}
}

type ScriptError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ScriptErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=scripts.ScriptErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptError) Reset() {
	*x = ScriptError{}
	mi := &file_scripts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptError) ProtoMessage() {}

func (x *ScriptError) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptError.ProtoReflect.Descriptor instead.
func (*ScriptError) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptError) GetCode() ScriptErrorCode {
	if x != nil {
		return x.Code
	}
	return ScriptErrorCode_ID_MALFORMED
}

func (x *ScriptError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Scripts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []*Script              `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scripts) Reset() {
	*x = Scripts{}
	mi := &file_scripts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scripts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scripts) ProtoMessage() {}

func (x *Scripts) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scripts.ProtoReflect.Descriptor instead.
func (*Scripts) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{1}
}

func (x *Scripts) GetScripts() []*Script {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type Script struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Divisions     []*Division            `protobuf:"bytes,4,rep,name=divisions,proto3" json:"divisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Script) Reset() {
	*x = Script{}
	mi := &file_scripts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{2}
}

func (x *Script) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Script) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Script) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Script) GetDivisions() []*Division {
	if x != nil {
		return x.Divisions
	}
	return nil
}

type Division struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PreviousTotals []uint32               `protobuf:"varint,3,rep,packed,name=previousTotals,proto3" json:"previousTotals,omitempty"`
	TextCues       []*TextCuePair         `protobuf:"bytes,4,rep,name=textCues,proto3" json:"textCues,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Division) Reset() {
	*x = Division{}
	mi := &file_scripts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Division) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Division) ProtoMessage() {}

func (x *Division) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Division.ProtoReflect.Descriptor instead.
func (*Division) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{3}
}

func (x *Division) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Division) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Division) GetPreviousTotals() []uint32 {
	if x != nil {
		return x.PreviousTotals
	}
	return nil
}

func (x *Division) GetTextCues() []*TextCuePair {
	if x != nil {
		return x.TextCues
	}
	return nil
}

type TextCuePair struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Request        *TextCue               `protobuf:"bytes,1,opt,name=request,proto3,oneof" json:"request,omitempty"`
	Response       *TextCue               `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	PreviousScores []uint32               `protobuf:"varint,3,rep,packed,name=previousScores,proto3" json:"previousScores,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TextCuePair) Reset() {
	*x = TextCuePair{}
	mi := &file_scripts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCuePair) ProtoMessage() {}

func (x *TextCuePair) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCuePair.ProtoReflect.Descriptor instead.
func (*TextCuePair) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{4}
}

func (x *TextCuePair) GetRequest() *TextCue {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TextCuePair) GetResponse() *TextCue {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TextCuePair) GetPreviousScores() []uint32 {
	if x != nil {
		return x.PreviousScores
	}
	return nil
}

type TextCue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []string               `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCue) Reset() {
	*x = TextCue{}
	mi := &file_scripts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCue) ProtoMessage() {}

func (x *TextCue) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCue.ProtoReflect.Descriptor instead.
func (*TextCue) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{5}
}

func (x *TextCue) GetActors() []string {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *TextCue) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DivisionScoreUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=scriptId,proto3" json:"scriptId,omitempty"`
	DivisionIdx   uint32                 `protobuf:"varint,2,opt,name=divisionIdx,proto3" json:"divisionIdx,omitempty"`
	NewScores     []uint32               `protobuf:"varint,3,rep,packed,name=newScores,proto3" json:"newScores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivisionScoreUpdate) Reset() {
	*x = DivisionScoreUpdate{}
	mi := &file_scripts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivisionScoreUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivisionScoreUpdate) ProtoMessage() {}

func (x *DivisionScoreUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivisionScoreUpdate.ProtoReflect.Descriptor instead.
func (*DivisionScoreUpdate) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{6}
}

func (x *DivisionScoreUpdate) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *DivisionScoreUpdate) GetDivisionIdx() uint32 {
	if x != nil {
		return x.DivisionIdx
	}
	return 0
}

func (x *DivisionScoreUpdate) GetNewScores() []uint32 {
	if x != nil {
		return x.NewScores
	}
	return nil
}

type ScriptNameUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=scriptId,proto3" json:"scriptId,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptNameUpdate) Reset() {
	*x = ScriptNameUpdate{}
	mi := &file_scripts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptNameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptNameUpdate) ProtoMessage() {}

func (x *ScriptNameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptNameUpdate.ProtoReflect.Descriptor instead.
func (*ScriptNameUpdate) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{7}
}

func (x *ScriptNameUpdate) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *ScriptNameUpdate) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

var File_scripts_proto protoreflect.FileDescriptor

const file_scripts_proto_rawDesc = "" +
	"\n" +
	"\rscripts.proto\x12\ascripts\"U\n" +
	"\vScriptError\x12,\n" +
	"\x04code\x18\x01 \x01(\x0e2\x18.scripts.ScriptErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\aScripts\x12)\n" +
	"\ascripts\x18\x01 \x03(\v2\x0f.scripts.ScriptR\ascripts\"\x7f\n" +
	"\x06Script\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\x03R\tcreatedAt\x12/\n" +
	"\tdivisions\x18\x04 \x03(\v2\x11.scripts.DivisionR\tdivisions\"\x9a\x01\n" +
	"\bDivision\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12&\n" +
	"\x0epreviousTotals\x18\x03 \x03(\rR\x0epreviousTotals\x120\n" +
	"\btextCues\x18\x04 \x03(\v2\x14.scripts.TextCuePairR\btextCues\"\xa0\x01\n" +
	"\vTextCuePair\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x10.scripts.TextCueH\x00R\arequest\x88\x01\x01\x12,\n" +
	"\bresponse\x18\x02 \x01(\v2\x10.scripts.TextCueR\bresponse\x12&\n" +
	"\x0epreviousScores\x18\x03 \x03(\rR\x0epreviousScoresB\n" +
	"\n" +
	"\b_request\"5\n" +
	"\aTextCue\x12\x16\n" +
	"\x06actors\x18\x01 \x03(\tR\x06actors\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"q\n" +
	"\x13DivisionScoreUpdate\x12\x1a\n" +
	"\bscriptId\x18\x01 \x01(\tR\bscriptId\x12 \n" +
	"\vdivisionIdx\x18\x02 \x01(\rR\vdivisionIdx\x12\x1c\n" +
	"\tnewScores\x18\x03 \x03(\rR\tnewScores\"H\n" +
	"\x10ScriptNameUpdate\x12\x1a\n" +
	"\bscriptId\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\anewName\x18\x02 \x01(\tR\anewName*\x84\x01\n" +
	"\x0fScriptErrorCode\x12\x10\n" +
	"\fID_MALFORMED\x10\x00\x12\x12\n" +
	"\x0eUNKNOWN_SCRIPT\x10\x01\x12\x1a\n" +
	"\x16DIVISION_OUT_OF_BOUNDS\x10\x02\x12\x16\n" +
	"\x12INVALID_SCORE_DATA\x10\x03\x12\x17\n" +
	"\x13INVALID_SCRIPT_NAME\x10\x04B)Z'github.com/stausee1337/quipt/gen/protosb\x06proto3"

var (
	file_scripts_proto_rawDescOnce sync.Once
	file_scripts_proto_rawDescData []byte
)

func file_scripts_proto_rawDescGZIP() []byte {
	file_scripts_proto_rawDescOnce.Do(func() {
		file_scripts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scripts_proto_rawDesc), len(file_scripts_proto_rawDesc)))
	})
	return file_scripts_proto_rawDescData
}

var file_scripts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scripts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_scripts_proto_goTypes = []any{
	(ScriptErrorCode)(0),        // 0: scripts.ScriptErrorCode
	(*ScriptError)(nil),         // 1: scripts.ScriptError
	(*Scripts)(nil),             // 2: scripts.Scripts
	(*Script)(nil),              // 3: scripts.Script
	(*Division)(nil),            // 4: scripts.Division
	(*TextCuePair)(nil),         // 5: scripts.TextCuePair
	(*TextCue)(nil),             // 6: scripts.TextCue
	(*DivisionScoreUpdate)(nil), // 7: scripts.DivisionScoreUpdate
	(*ScriptNameUpdate)(nil),    // 8: scripts.ScriptNameUpdate
}
var file_scripts_proto_depIdxs = []int32{
	0, // 0: scripts.ScriptError.code:type_name -> scripts.ScriptErrorCode
	3, // 1: scripts.Scripts.scripts:type_name -> scripts.Script
	4, // 2: scripts.Script.divisions:type_name -> scripts.Division
	5, // 3: scripts.Division.textCues:type_name -> scripts.TextCuePair
	6, // 4: scripts.TextCuePair.request:type_name -> scripts.TextCue
	6, // 5: scripts.TextCuePair.response:type_name -> scripts.TextCue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_scripts_proto_init() }
func file_scripts_proto_init() {
	if File_scripts_proto != nil {
		return
	}
	file_scripts_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scripts_proto_rawDesc), len(file_scripts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scripts_proto_goTypes,
		DependencyIndexes: file_scripts_proto_depIdxs,
		EnumInfos:         file_scripts_proto_enumTypes,
		MessageInfos:      file_scripts_proto_msgTypes,
	}.Build()
	File_scripts_proto = out.File
	file_scripts_proto_goTypes = nil
	file_scripts_proto_depIdxs = nil
}
