// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: scripts.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scripts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []*Script              `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scripts) Reset() {
	*x = Scripts{}
	mi := &file_scripts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scripts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scripts) ProtoMessage() {}

func (x *Scripts) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scripts.ProtoReflect.Descriptor instead.
func (*Scripts) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{0}
}

func (x *Scripts) GetScripts() []*Script {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type Script struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Divisions     []*Division            `protobuf:"bytes,3,rep,name=divisions,proto3" json:"divisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Script) Reset() {
	*x = Script{}
	mi := &file_scripts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{1}
}

func (x *Script) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Script) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Script) GetDivisions() []*Division {
	if x != nil {
		return x.Divisions
	}
	return nil
}

type Division struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PreviousTotals []uint32               `protobuf:"varint,3,rep,packed,name=previousTotals,proto3" json:"previousTotals,omitempty"`
	TextCues       []*TextCuePair         `protobuf:"bytes,4,rep,name=textCues,proto3" json:"textCues,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Division) Reset() {
	*x = Division{}
	mi := &file_scripts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Division) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Division) ProtoMessage() {}

func (x *Division) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Division.ProtoReflect.Descriptor instead.
func (*Division) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{2}
}

func (x *Division) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Division) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Division) GetPreviousTotals() []uint32 {
	if x != nil {
		return x.PreviousTotals
	}
	return nil
}

func (x *Division) GetTextCues() []*TextCuePair {
	if x != nil {
		return x.TextCues
	}
	return nil
}

type TextCuePair struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Request        *TextCue               `protobuf:"bytes,1,opt,name=request,proto3,oneof" json:"request,omitempty"`
	Response       *TextCue               `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	PreviousScores []uint32               `protobuf:"varint,3,rep,packed,name=previousScores,proto3" json:"previousScores,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TextCuePair) Reset() {
	*x = TextCuePair{}
	mi := &file_scripts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCuePair) ProtoMessage() {}

func (x *TextCuePair) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCuePair.ProtoReflect.Descriptor instead.
func (*TextCuePair) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{3}
}

func (x *TextCuePair) GetRequest() *TextCue {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TextCuePair) GetResponse() *TextCue {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TextCuePair) GetPreviousScores() []uint32 {
	if x != nil {
		return x.PreviousScores
	}
	return nil
}

type TextCue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *string                `protobuf:"bytes,1,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCue) Reset() {
	*x = TextCue{}
	mi := &file_scripts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCue) ProtoMessage() {}

func (x *TextCue) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCue.ProtoReflect.Descriptor instead.
func (*TextCue) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{4}
}

func (x *TextCue) GetActor() string {
	if x != nil && x.Actor != nil {
		return *x.Actor
	}
	return ""
}

func (x *TextCue) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_scripts_proto protoreflect.FileDescriptor

const file_scripts_proto_rawDesc = "" +
	"\n" +
	"\rscripts.proto\x12\ascripts\"4\n" +
	"\aScripts\x12)\n" +
	"\ascripts\x18\x01 \x03(\v2\x0f.scripts.ScriptR\ascripts\"a\n" +
	"\x06Script\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\tdivisions\x18\x03 \x03(\v2\x11.scripts.DivisionR\tdivisions\"\x8c\x01\n" +
	"\bDivision\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0epreviousTotals\x18\x03 \x03(\rR\x0epreviousTotals\x120\n" +
	"\btextCues\x18\x04 \x03(\v2\x14.scripts.TextCuePairR\btextCues\"\xa0\x01\n" +
	"\vTextCuePair\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x10.scripts.TextCueH\x00R\arequest\x88\x01\x01\x12,\n" +
	"\bresponse\x18\x02 \x01(\v2\x10.scripts.TextCueR\bresponse\x12&\n" +
	"\x0epreviousScores\x18\x03 \x03(\rR\x0epreviousScoresB\n" +
	"\n" +
	"\b_request\"B\n" +
	"\aTextCue\x12\x19\n" +
	"\x05actor\x18\x01 \x01(\tH\x00R\x05actor\x88\x01\x01\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textB\b\n" +
	"\x06_actorB)Z'github.com/stausee1337/quipt/gen/protosb\x06proto3"

var (
	file_scripts_proto_rawDescOnce sync.Once
	file_scripts_proto_rawDescData []byte
)

func file_scripts_proto_rawDescGZIP() []byte {
	file_scripts_proto_rawDescOnce.Do(func() {
		file_scripts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scripts_proto_rawDesc), len(file_scripts_proto_rawDesc)))
	})
	return file_scripts_proto_rawDescData
}

var file_scripts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scripts_proto_goTypes = []any{
	(*Scripts)(nil),     // 0: scripts.Scripts
	(*Script)(nil),      // 1: scripts.Script
	(*Division)(nil),    // 2: scripts.Division
	(*TextCuePair)(nil), // 3: scripts.TextCuePair
	(*TextCue)(nil),     // 4: scripts.TextCue
}
var file_scripts_proto_depIdxs = []int32{
	1, // 0: scripts.Scripts.scripts:type_name -> scripts.Script
	2, // 1: scripts.Script.divisions:type_name -> scripts.Division
	3, // 2: scripts.Division.textCues:type_name -> scripts.TextCuePair
	4, // 3: scripts.TextCuePair.request:type_name -> scripts.TextCue
	4, // 4: scripts.TextCuePair.response:type_name -> scripts.TextCue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_scripts_proto_init() }
func file_scripts_proto_init() {
	if File_scripts_proto != nil {
		return
	}
	file_scripts_proto_msgTypes[3].OneofWrappers = []any{}
	file_scripts_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scripts_proto_rawDesc), len(file_scripts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scripts_proto_goTypes,
		DependencyIndexes: file_scripts_proto_depIdxs,
		MessageInfos:      file_scripts_proto_msgTypes,
	}.Build()
	File_scripts_proto = out.File
	file_scripts_proto_goTypes = nil
	file_scripts_proto_depIdxs = nil
}
